### ISSUE TITLE
Upgrading to latest 1.0.22 from previous 0.90.0 build issues

### ISSUE THREAD

**Issue by kerriganb** [npolyak/NP.Avalonia.UniDock#2]
Hi Nick, i recently upgraded to latest unidock (on mac - btw windows works fine and builds correctly) ... when i now try to build ...i get the following build error

/Projects/avalonia/unidock/NP.Avalonia.Demos/NP.Demos.UniDockIntroductionDemo/MainWindow.axaml(6,6): Error XAMLIL: Unable to resolve type SimpleDockGroup from namespace https://np.com/visuals Line 29, position 6. (XAMLIL) (NP.Demos.UniDockIntroductionDemo) Avalonia

(previously version on mac builds fine - 0.90.0)

i'm attaching screen shots if that might help. please let me know if you need any other info...

thanks

<img width="1680" alt="Screen Shot 2022-01-12 at 6 49 22 PM" src="https://user-images.githubusercontent.com/5913794/149261940-ad9aabce-0ace-4af2-a227-891a6f6f2911.png">

kerrigan. 
<img width="1680" alt="Screen Shot 2022-01-12 at 6 47 59 PM" src="https://user-images.githubusercontent.com/5913794/149261928-ace49795-ec3b-444c-960b-0715328eab5a.png">

**Comment by npolyak** [comment]
Hey Kerrigan, I'll take a look by the end of tomorrow

**Comment by npolyak** [comment]
Hey Kerrigan, 
sorry for the delay answering you. I think it is a problem with demo only. I renamed SimpleDockGroup to RootDockGroup - because it is a root group for every floating window. (Before it was called Simple because it can have only one child). 
I have not updated the demos from the first article [UniDock  Introduction](https://www.codeproject.com/Articles/5311587/UniDock-New-Multiplatform-Docking-Framework-Introd), but you should be able to use all demos from the second article - [UniDock Power Features](https://www.codeproject.com/Articles/5316702/UniDock-A-New-Multiplatform-UI-Docking-Framework-U). I'll try to fix the demos for the first article soon (time permitting).

**Comment by kerriganb** [comment]
ah, no worries. I'll give it a shot and let you know. thank you!
